return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 24,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 82,
  properties = {},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../manpac/assets/maps/couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 24,
      height = 24,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "UwAAAFUAAABTAAAAVQAAAG0AAABtAAAAbQAAAFUAAABtAAAAcQAAAFUAAABVAAAAOQAAADkAAABVAAAAVwAAAFUAAABxAAAAcQAAAHEAAABxAAAAcQAAAFUAAABtAAAAcQAAAFUAAABxAAAANgAAAG0AAABVAAAAbQAAADYAAABVAAAAcQAAADsAAAA7AAAAPQAAAFUAAABvAAAAcQAAADsAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABtAAAAcQAAADYAAABxAAAAVQAAAFUAAABvAAAAcQAAAFUAAABvAAAAVQAAAG0AAABVAAAAVwAAAFUAAABXAAAAVQAAAHEAAABvAAAAcQAAADsAAAA7AAAAVQAAAG8AAABtAAAAOQAAAFUAAABtAAAAbwAAADYAAABVAAAAcQAAADYAAABxAAAANgAAAFUAAAA7AAAAcQAAADsAAABxAAAAbwAAAFUAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABVAAAAcQAAADYAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAG8AAABvAAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADYAAAA2AAAAcQAAADYAAABVAAAAcQAAAG8AAABxAAAAOwAAAFUAAABxAAAAbwAAAFUAAAA5AAAAVQAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAADsAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADsAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFcAAABVAAAAVQAAAHEAAAA7AAAAbwAAAHEAAAA7AAAAVQAAADkAAAA2AAAANgAAADYAAABvAAAAcQAAAFUAAABVAAAAcQAAAG8AAABxAAAAVQAAAHEAAABvAAAAVQAAAFcAAABvAAAAVQAAAG0AAABVAAAAVQAAAFUAAABtAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABvAAAAVQAAAHEAAABVAAAAbwAAAFUAAABxAAAAVQAAAFUAAABVAAAAbwAAAG0AAAA7AAAAOwAAADsAAABVAAAAOwAAAHEAAABVAAAAOwAAADsAAABvAAAAVQAAADsAAAA5AAAAbwAAAHEAAABVAAAAbQAAADsAAABxAAAAbwAAAG8AAABVAAAAcQAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFUAAAA7AAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAcQAAADsAAAA7AAAAVQAAAG0AAABVAAAAcQAAAFUAAAA7AAAAcQAAAG8AAAA5AAAAVQAAAD0AAAA7AAAAOwAAADsAAABxAAAAcQAAADsAAAA7AAAAOwAAAHEAAABvAAAAVQAAAFUAAABxAAAAOwAAAFUAAAA7AAAAcQAAAFUAAABxAAAAVQAAAFMAAABVAAAAbwAAAEoAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAG0AAABVAAAAbwAAAG8AAABxAAAAVQAAAG8AAABVAAAAcQAAADsAAABxAAAAVQAAAFMAAABvAAAAVQAAAFcAAAA7AAAAOwAAAHEAAABVAAAAOwAAAHEAAAA7AAAAOwAAAH4AAABvAAAAVQAAAFUAAABtAAAAVQAAAG0AAABvAAAAcQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAAGQAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABVAAAAVQAAAFUAAABtAAAAOwAAADsAAABtAAAAOwAAAFUAAABVAAAAcQAAAFUAAAA7AAAAOwAAADkAAABvAAAAcAAAAHEAAAA2AAAANgAAADYAAAA2AAAAcQAAADYAAAA2AAAAVQAAAG8AAABtAAAAcQAAAFUAAABVAAAAVQAAAFUAAAA7AAAAVwAAADsAAABxAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADsAAAA7AAAAOwAAADsAAABxAAAAVQAAAFUAAABVAAAAbwAAAHEAAAA2AAAANgAAADYAAAA2AAAAVQAAAHEAAAA2AAAANgAAAFUAAABVAAAAVQAAAHEAAAA2AAAAVQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAADsAAAA7AAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADYAAAA2AAAAbwAAAFUAAABxAAAAbwAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAAFUAAABTAAAAOwAAADsAAABxAAAAVQAAADsAAAA5AAAAVQAAAHEAAABvAAAAVQAAAFUAAABxAAAAVQAAAG8AAABxAAAAVQAAAHEAAABVAAAAUwAAAFUAAABTAAAAVQAAAG8AAABVAAAAVQAAADkAAABVAAAAVQAAAFMAAABVAAAAOwAAAHEAAABVAAAAOwAAAFUAAABxAAAAbwAAAFUAAABxAAAAbwAAAHEAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABvAAAAOwAAAHEAAABVAAAAOwAAAHEAAABVAAAAUwAAAFUAAABVAAAAUwAAAG8AAABxAAAAVQAAAG8AAABxAAAAcQAAAFUAAABVAAAAUwAAAG8AAABVAAAAVQAAAFMAAABVAAAAVQAAAHEAAAA7AAAAVQAAAFMAAABVAAAAUwAAAFUAAABvAAAAbQAAAFUAAABTAAAAbwAAAHEAAABVAAAAcQAAAG8AAAA7AAAAPQAAAFUAAABvAAAAbwAAAG0AAABvAAAAbwAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAG8AAABtAAAAVQAAAG8AAABVAAAAfgAAAFUAAABvAAAA"
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["sorties"] = ""
      },
      objects = {
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 1471,
          width = 65,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 961,
          y = 1472,
          width = 63,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 578,
          y = 1473,
          width = 62,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 194,
          y = 1473,
          width = 63,
          height = 71,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 1344,
          width = 61,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1216,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 1407,
          width = 61,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 1472,
          width = 61,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 63,
          y = 1472,
          width = 65,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129,
          y = 1472,
          width = 63,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 321,
          y = 1473,
          width = 60,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 446,
          y = 1473,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 383,
          y = 1472,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 513,
          y = 1473,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 897,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1025,
          y = 1471,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1091,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1471,
          y = 1343,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1277,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1471,
          y = 1215,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1152,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1087,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 959,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 894,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 831,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 703,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 320,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 124,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 60,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 1,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1278,
          y = 0,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1215,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1151,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 769,
          y = 1,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129,
          y = 0,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 62,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 124,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 190,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 253,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 384,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 576,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 639,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 702,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 832,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 959,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1021,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 1084,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
