return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.15.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 35,
  height = 35,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 98,
  properties = {},
  tilesets = {
    {
      name = "couloirs_64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 97,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 136,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 35,
      height = 35,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "iQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAYgAAAGIAAABiAAAAbwAAAG8AAABVAAAAbwAAAG8AAABiAAAAYgAAAG8AAABvAAAAbwAAAG8AAABvAAAAVQAAAGIAAABvAAAAbwAAAG8AAABvAAAAVQAAAG8AAABvAAAAbwAAAG8AAABVAAAAiQAAAIkAAABVAAAAVQAAADkAAABVAAAAYgAAAGIAAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAOQAAAFUAAABiAAAAYgAAADkAAABiAAAAbwAAADkAAABVAAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAAGIAAACJAAAAiQAAAGIAAABiAAAAOQAAAGIAAABvAAAAbwAAADkAAAA5AAAAYgAAAFUAAABvAAAAbwAAAG8AAAA5AAAAVQAAAGIAAAA5AAAAYgAAAG8AAABvAAAAOQAAAG8AAAA5AAAAOQAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABiAAAAbwAAAIkAAACJAAAAbwAAAG8AAAA5AAAAbwAAAGIAAABVAAAAYgAAADkAAABvAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAbwAAADkAAABvAAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAAA5AAAAVQAAAG8AAAA5AAAAiQAAAIkAAAA5AAAAYgAAAFUAAAA5AAAAbwAAAGIAAABvAAAAOQAAADkAAABvAAAAbwAAAGIAAABVAAAAOQAAAGIAAAA5AAAAYgAAAFUAAAA5AAAAYgAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAACJAAAAiQAAADkAAABvAAAAYgAAAGIAAAA5AAAAbwAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAbwAAADkAAABvAAAAYgAAAGIAAABvAAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAbwAAAG8AAABvAAAAOQAAAIkAAACJAAAAVQAAADkAAABvAAAAbwAAADkAAABiAAAAVQAAADkAAABiAAAAYgAAADkAAAA5AAAAbwAAADkAAABVAAAAOQAAADkAAABvAAAAbwAAADkAAABvAAAAOQAAAGIAAAA5AAAAYgAAAGIAAAA5AAAAbwAAADkAAABVAAAAVQAAADkAAABVAAAAiQAAAIkAAABVAAAAYgAAADkAAABVAAAAOQAAAG8AAABiAAAAOQAAAG8AAABvAAAAOQAAADkAAAA5AAAAVQAAAGIAAAA5AAAAVQAAADkAAAA5AAAAOQAAAFUAAABiAAAAbwAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAOQAAAFUAAACJAAAAiQAAAGIAAABvAAAAVQAAAGIAAAA5AAAAOQAAAG8AAAA5AAAAOQAAAGIAAABVAAAAYgAAADkAAABiAAAAbwAAAGIAAABiAAAAYgAAADkAAABiAAAAYgAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAbwAAAG8AAAA5AAAAVQAAAIkAAACJAAAAbwAAADkAAABiAAAAbwAAADkAAABVAAAAYgAAADkAAAA5AAAAbwAAAGIAAABvAAAAVQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAOQAAAGIAAABiAAAAOQAAAFUAAAA5AAAAYgAAAG8AAABiAAAAVQAAADkAAABiAAAAiQAAAIkAAAA5AAAAOQAAAG8AAAA5AAAAYgAAAGIAAABvAAAAOQAAAFUAAAA5AAAAbwAAADkAAABiAAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAABiAAAAYgAAAG8AAACJAAAAiQAAAGIAAABiAAAAYgAAAGIAAABvAAAAbwAAADkAAABVAAAAYgAAADkAAAA5AAAAOQAAAG8AAABiAAAAOQAAAGIAAABvAAAAbwAAADkAAABiAAAAYgAAADkAAABiAAAAVQAAADkAAABiAAAAOQAAAFUAAAA5AAAAOQAAAG8AAABvAAAAOQAAAIkAAACJAAAAbwAAAG8AAABvAAAAbwAAAFUAAABVAAAAOQAAAGIAAABvAAAAOQAAAFUAAABiAAAAOQAAAG8AAAA5AAAAbwAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAG8AAABiAAAAYgAAAG8AAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAiQAAAIkAAAA5AAAAOQAAAFUAAAA5AAAAYgAAAGIAAAA5AAAAbwAAADkAAABiAAAAYgAAAG8AAABVAAAAYgAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAG8AAABiAAAAOQAAAFUAAAA5AAAAYgAAAFUAAACJAAAAiQAAADkAAABiAAAAVQAAADkAAABvAAAAbwAAADkAAAA5AAAAOQAAAG8AAABvAAAAOQAAAFUAAABvAAAAOQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAYgAAAFUAAABiAAAAOQAAAG8AAAA5AAAAYgAAAGIAAABvAAAAYgAAAIkAAACJAAAAOQAAAG8AAABiAAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAYgAAADkAAABiAAAAYgAAADkAAABVAAAAbwAAADkAAAA5AAAAVQAAADkAAABvAAAAYgAAAG8AAABVAAAAVQAAADkAAABvAAAAbwAAADkAAABvAAAAiQAAAIkAAABVAAAAOQAAAG8AAABiAAAAYgAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABvAAAAOQAAAG8AAABvAAAAYgAAAGIAAABiAAAAOQAAADkAAABiAAAAOQAAADkAAABvAAAAOQAAAGIAAABiAAAAOQAAAFUAAABiAAAAOQAAADkAAACJAAAAiQAAAGIAAABiAAAAYgAAAG8AAABvAAAAOQAAADkAAABiAAAAVQAAADkAAABiAAAAVQAAAGIAAAA5AAAAVQAAAFUAAABvAAAAbwAAAG8AAABVAAAAOQAAAG8AAABiAAAAYgAAAGIAAABiAAAAbwAAAG8AAAA5AAAAVQAAAG8AAABVAAAAVQAAAIkAAACJAAAAbwAAAG8AAABvAAAAOQAAAFUAAABVAAAAOQAAAG8AAABiAAAAYgAAAG8AAABiAAAAbwAAADkAAABiAAAAYgAAADkAAAA5AAAAVQAAAGIAAAA5AAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAiQAAAIkAAAA5AAAAYgAAAFUAAAA5AAAAYgAAAGIAAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAAA5AAAAVQAAAG8AAABvAAAAVQAAADkAAABiAAAAbwAAAGIAAABVAAAAYgAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAAG8AAAA5AAAAbwAAAG8AAACJAAAAiQAAAFUAAABvAAAAYgAAAGIAAABvAAAAbwAAAFUAAABiAAAAYgAAADkAAABVAAAAVQAAADkAAABiAAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAbwAAAGIAAABvAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAIkAAACJAAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAYgAAAG8AAABvAAAAOQAAAGIAAABiAAAAOQAAAG8AAABiAAAAOQAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAADkAAABiAAAAYgAAADkAAAA5AAAAOQAAAFUAAABiAAAAOQAAAFUAAAA5AAAAiQAAAIkAAABVAAAAOQAAADkAAAA5AAAAVQAAADkAAABvAAAAOQAAAFUAAABiAAAAbwAAAG8AAABVAAAAOQAAAG8AAAA5AAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAVQAAAFUAAAA5AAAAYgAAAG8AAAA5AAAAVQAAADkAAACJAAAAiQAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAADkAAABiAAAAYgAAAG8AAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAVQAAADkAAABvAAAAbwAAAG8AAABVAAAAYgAAADkAAABiAAAAYgAAADkAAABvAAAAOQAAADkAAABiAAAAOQAAAIkAAACJAAAAbwAAAFUAAABiAAAAOQAAAG8AAABvAAAAOQAAADkAAAA5AAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAGIAAABiAAAAOQAAADkAAAA5AAAAYgAAAGIAAABvAAAAOQAAAG8AAABvAAAAOQAAAGIAAABVAAAAYgAAAG8AAAA5AAAAiQAAAIkAAAA5AAAAYgAAAG8AAABVAAAAVQAAADkAAAA5AAAAVQAAADkAAAA5AAAAYgAAAGIAAAA5AAAAYgAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABiAAAAYgAAAGIAAABiAAAAbwAAAGIAAABvAAAAVQAAADkAAACJAAAAiQAAADkAAABvAAAAOQAAAGIAAABiAAAAOQAAADkAAABVAAAAOQAAADkAAABvAAAAbwAAADkAAABvAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAYgAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAABVAAAAOQAAAIkAAACJAAAAVQAAAGIAAABiAAAAbwAAAG8AAAA5AAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAbwAAAGIAAABVAAAAOQAAAGIAAABvAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAABVAAAAOQAAAGIAAABiAAAAiQAAAIkAAABiAAAAbwAAAG8AAAA5AAAAVQAAAGIAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAbwAAAGIAAABVAAAAbwAAAG8AAABvAAAAYgAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAbwAAAG8AAACJAAAAiQAAAG8AAAA5AAAAVQAAADkAAABVAAAAbwAAADkAAAA5AAAAOQAAAFUAAAA5AAAAVQAAAGIAAAA5AAAAVQAAADkAAAA5AAAAbwAAADkAAAA5AAAAbwAAAGIAAABiAAAAOQAAADkAAABvAAAAYgAAADkAAABvAAAAbwAAAGIAAABiAAAAVQAAAIkAAACJAAAAOQAAAFUAAABiAAAAOQAAAGIAAAA5AAAAVQAAAFUAAAA5AAAAVQAAADkAAABVAAAAbwAAADkAAABiAAAAYgAAADkAAABVAAAAYgAAAGIAAAA5AAAAbwAAAG8AAABVAAAAVQAAADkAAABvAAAAVQAAADkAAAA5AAAAbwAAAG8AAABVAAAAiQAAAIkAAAA5AAAAYgAAAG8AAAA5AAAAbwAAADkAAABiAAAAYgAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAAG8AAABvAAAAOQAAAGIAAABvAAAAbwAAAFUAAAA5AAAAOQAAAGIAAABiAAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAACJAAAAiQAAADkAAABVAAAAVQAAAFUAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAAA5AAAAbwAAADkAAABVAAAAVQAAAFUAAAA5AAAAbwAAADkAAABVAAAAVQAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAVQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAA=="
    },
    {
      type = "objectgroup",
      name = "spawn_hunter",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1108,
          y = 1032,
          width = 36,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1032,
          y = 1100,
          width = 40,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1100,
          y = 1172,
          width = 40,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1480,
          y = 1092,
          width = 44,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1288,
          y = 1088,
          width = 56,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawn_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.6667,
          y = 257.333,
          width = 61.3333,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1100,
          y = 452,
          width = 48,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1872,
          y = 1032,
          width = 44,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1100,
          y = 1680,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 464,
          y = 1104,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 72,
          width = 60,
          height = 53.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129.333,
          y = 73.3333,
          width = 64,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 193.333,
          y = 72,
          width = 61.3333,
          height = 54.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 257.333,
          y = 72,
          width = 61.3333,
          height = 53.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 322.667,
          y = 76,
          width = 61.3333,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 386.667,
          y = 74.6667,
          width = 58.6667,
          height = 50.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 641.333,
          y = 72,
          width = 65.3333,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 706.667,
          y = 70.6667,
          width = 60,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 72,
          width = 62.6667,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 894.667,
          y = 72,
          width = 62.6667,
          height = 50.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1089.33,
          y = 64,
          width = 64,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1153.33,
          y = 66.6667,
          width = 61.3333,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1213.33,
          y = 68,
          width = 66.6667,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1281.33,
          y = 70.6667,
          width = 62.6667,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 68,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1534.67,
          y = 70.6667,
          width = 68,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 72,
          width = 64,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1664,
          y = 80,
          width = 64,
          height = 49.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1729.33,
          y = 74.6667,
          width = 62.6667,
          height = 53.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1857.33,
          y = 69.3333,
          width = 61.3333,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 72,
          width = 64,
          height = 54.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1982.67,
          y = 72,
          width = 66.6667,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2046.67,
          y = 73.3333,
          width = 64,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2113.33,
          y = 204,
          width = 58.6667,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2117.33,
          y = 258.667,
          width = 57.3333,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 316,
          width = 57.3333,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2113.33,
          y = 376,
          width = 60,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2112,
          y = 710.667,
          width = 65.3333,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2108,
          y = 765.333,
          width = 68,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2113.33,
          y = 830.667,
          width = 62.6667,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 1033.33,
          width = 60,
          height = 53.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2113.33,
          y = 1089.33,
          width = 60,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2114.67,
          y = 1285.33,
          width = 58.6667,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2113.33,
          y = 1342.67,
          width = 61.3333,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2112,
          y = 1404,
          width = 62.6667,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2114.67,
          y = 1466.67,
          width = 61.3333,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 1529.33,
          width = 60,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2117.33,
          y = 1598.67,
          width = 57.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 1665.33,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2114.67,
          y = 1725.33,
          width = 61.3333,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2114.67,
          y = 1857.33,
          width = 60,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 2114.67,
          width = 58.6667,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 2114.67,
          width = 66.6667,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 2114.67,
          width = 62.6667,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1917.33,
          y = 2112,
          width = 66.6667,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1856,
          y = 2112,
          width = 64,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1793.33,
          y = 2113.33,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1665.33,
          y = 2116,
          width = 60,
          height = 54.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1598.67,
          y = 2113.33,
          width = 65.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 2112,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1476,
          y = 2114.67,
          width = 57.3333,
          height = 57.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 2116,
          width = 61.3333,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1150.67,
          y = 2112,
          width = 64,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 2113.33,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 830.667,
          y = 2112,
          width = 64,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 2113.33,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 702.667,
          y = 2114.67,
          width = 65.3333,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 2117.33,
          width = 64,
          height = 58.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 510.667,
          y = 2110.67,
          width = 61.3333,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 2113.33,
          width = 62.6667,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 386.667,
          y = 2113.33,
          width = 62.6667,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.3333,
          y = 2113.33,
          width = 61.3333,
          height = 62.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2048,
          width = 62.6667,
          height = 65.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.6667,
          y = 1988,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.3333,
          y = 1921.33,
          width = 62.6667,
          height = 65.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1730.67,
          width = 58.6667,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1665.33,
          width = 62.6667,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1604,
          width = 61.3333,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 62.6667,
          y = 1280,
          width = 65.3333,
          height = 65.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 62.6667,
          y = 1212,
          width = 65.3333,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.6667,
          y = 1024,
          width = 60,
          height = 65.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 958.667,
          width = 61.3333,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.3333,
          y = 896,
          width = 60,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 832,
          width = 60,
          height = 61.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 702.667,
          width = 62.6667,
          height = 65.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65.3333,
          y = 638.667,
          width = 62.6667,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66.6667,
          y = 385.333,
          width = 62.6667,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 62.6667,
          y = 317.333,
          width = 66.6667,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
